import Head from "next/head";

import SiteLogo from "/public/personal-site-logo.png"
import SiteLogoTp from "/public/personal-site-logo-tp.ico"

import ProfilePicture from "/public/main/ad-profile.jpg"

import LinkedInIcon from "/public/footer/linkedin-icon.png"
import GithubIcon from "/public/footer/github-icon.png"
import SandboxIcon from "/public/footer/codesandbox-icon.png"
import CodepenIcon from "/public/footer/codepen-icon.png"
import EmailIcon from "/public/footer/email-icon.png"

import mainStyles from "../styles/Home.module.sass";
import headerStyles from "../styles/Header.module.sass";
import footerStyles from "../styles/Footer.module.sass";

export default function Home() {
    return (
        <div className={mainStyles.container}>
            <Head>
                <title>Alex De Luca</title>
                <meta
                    name="Alex De Luca's personal website"
                    content="Generated by create next app"
                />
                <link rel="icon" href={SiteLogoTp.src} />
            </Head>

            <header className={headerStyles.header} id="header">
                <nav className={headerStyles.headerNav}>
                    <a href="#header">
                        <img
                            className={headerStyles.adLogo}
                            alt="Alex De Luca logo"
                            src={SiteLogo.src}
                        ></img>
                    </a>
                    <ul className={headerStyles.headerLinks}>
                        <li className={headerStyles.headerLink}>
                            <a href="#header">Home</a>
                        </li>
                        <li className={headerStyles.headerLink}>
                            <a href="#about">About</a>
                        </li>
                        <li className={headerStyles.headerLink}>
                            <a href="#resume">Resume</a>
                        </li>
                        <li className={headerStyles.headerLink}>
                            <a href="#work">Work</a>
                        </li>
                    </ul>
                </nav>
            </header>

            <main className={mainStyles.main}>
                <img
                    className={mainStyles.profilePic}
                    alt="Alex De Luca profile picture"
                    src={ProfilePicture.src}
                ></img>

                <p className={mainStyles.description}>
                    Alex De Luca
                    <p>(he/him)</p>
                    <code className={mainStyles.code}>
                        Software Engineer - &#123;Frontend Focused&#125;
                    </code>
                </p>
            </main>

            <footer className={footerStyles.footer}>
                <nav className={footerStyles.footerNav}>
                    <ul className={footerStyles.footerLinks}>
                        <li className={footerStyles.footerLink}>
                            <a
                                href="https://www.linkedin.com/in/alex-de-luca/"
                                target="_blank"
                            >
                                <img
                                    className={footerStyles.footerLinkImg}
                                    src={LinkedInIcon.src}
                                ></img>
                            </a>
                        </li>
                        <li className={footerStyles.footerLink}>
                            <a
                                href="https://github.com/AlexDeL8"
                                target="_blank"
                            >
                                <img
                                    className={footerStyles.footerLinkImg}
                                    src={GithubIcon.src}
                                ></img>
                            </a>
                        </li>
                        <li className={footerStyles.footerLink}>
                            <a
                                href="https://codesandbox.io/u/alexdel"
                                target="_blank"
                            >
                                <img
                                    className={footerStyles.footerLinkImg}
                                    src={SandboxIcon.src}
                                ></img>
                            </a>
                        </li>
                        <li className={footerStyles.footerLink}>
                            <a
                                href="https://codepen.io/AlexDeL"
                                target="_blank"
                            >
                                <img
                                    className={footerStyles.footerLinkImg}
                                    src={CodepenIcon.src}
                                ></img>
                            </a>
                        </li>
                        <li className={footerStyles.footerLink}>
                            <a href="mailto:alexnaj88@gmail.com">
                                <img
                                    className={footerStyles.footerLinkImg}
                                    src={EmailIcon.src}
                                ></img>
                            </a>
                        </li>
                    </ul>
                </nav>
            </footer>
        </div>
    );
}
