import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Alex De Luca</title>
                <meta
                    name="Alex De Luca's personal website"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/personal-site-logo-tp.ico" />
            </Head>

            <header>
                <nav className="HeaderNav">
                    <ul className="HeaderLinks">
                        <li className="HeaderLink">
                            <a>Home</a>
                        </li>
                        <li className="HeaderLink">
                            <a>About</a>
                        </li>
                        <li className="HeaderLink">
                            <a>Resume</a>
                        </li>
                        <li className="HeaderLink">
                            <a>Work</a>
                        </li>
                    </ul>
                </nav>
            </header>

            <main className={styles.main}>
                <img
                    className={styles.profilePic}
                    alt="Alex De Luca profile picture"
                    src="/main/ad-profile.jpg"
                ></img>

                <p className={styles.description}>
                    Alex De Luca <br></br>
                    <code className={styles.code}>
                        Software Engineer - &#123;Frontend Focused&#125;
                    </code>
                </p>
            </main>

            <footer className={styles.footer}>
                <nav className="FooterNav">
                    <ul className="FooterLinks">
                        <li className="FooterLink">
                            <a
                                href="https://www.linkedin.com/in/alex-de-luca/"
                                target="_blank"
                            >
                                LinkedIn
                            </a>
                        </li>
                        <li className="FooterLink">
                            <a
                                href="https://github.com/AlexDeL8"
                                target="_blank"
                            >
                                Github
                            </a>
                        </li>
                        <li className="FooterLink">
                            <a
                                href="https://codesandbox.io/u/alexdel"
                                target="_blank"
                            >
                                CodeSandbox
                            </a>
                        </li>
                        <li className="FooterLink">
                            <a
                                href="https://codepen.io/AlexDeL"
                                target="_blank"
                            >
                                CodePen
                            </a>
                        </li>
                        <li className="FooterLink">
                            <a href="mailto:alexnaj88@gmail.com">Email</a>
                        </li>
                    </ul>
                </nav>
            </footer>
        </div>
    );
}
